### ISSUE TITLE
找不到API key和token+1

### ISSUE THREAD

**Issue by ghost** [Jincheng-Gong/Bookshelf-VitalSource-Downloader-Killer#2]

**Comment by Matrix-JCG** [comment]
用fiddler4来抓包，具体的使用教程百度一下就行，在Header里可以找到API key和token，抱歉现在才看到留言。

**Comment by TKTD-Zhu** [comment]
谢了，但是我已经成功说服教授不再用那个流氓软件了。

**Comment by Matrix-JCG** [comment]
哈哈哈哈哈哈，不过这个方法弄出来的也不是true pdf，不够清晰，现在也没找到无痛的办法处理这玩意。
